apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kamal-deployment
  namespace: kamal
spec:
  selector:
    matchLabels:
      app: kamal
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: kamal
    spec:
      containers:
      - name: kamal
        image: 349948765351.dkr.ecr.ap-south-1.amazonaws.com/kamal:latest
        ports:
        - containerPort: 80
